export const textOne = `Se você está lendo esse post e não tem ideia do que seja Young Royals, chegou a hora de se atualizar. A produção sueca e original da Netflix tem conquistado o coração de adolescentes ao redor de todo o mundo e, principalmente, corações brasileiros.

Os motivos pelos quais a série está fazendo sucesso ficam óbvios no desenvolver do romance entre Simon — jovem de origem humilde — e Wilhelm, príncipe herdeiro da Suécia que é obrigado a se mudar para um internato, onde conhece Simon. O desenrolar disso tudo você já pode imaginar, né? Por isso, hoje queremos propor uma reflexão sobre a representatividade presente para além da comunidade LGBTQIA+.

Wilhelm entra num processo de autoconhecimento ao se mudar de escola, reconhecendo partes de si mesmo que nunca tinha notado. A produção aborda de forma muito real o processo de descobrimento e enfrentamento de questões e pensamentos que o invisibilizavam como jovem LGBTQIA+. Antes que os outros nos invisibilizem, sempre somos nós os primeiros a duvidar de nossas sexualidades e identidades. Com Wilhelm não foi diferente; até porque, onde já se viu um príncipe herdeiro não ser hétero?

Young Royals é, definitivamente, uma série real. Os personagens — héteros ou não — são adolescentes e agem como tal; não possuem corpos e rostos perfeitos, mostrando suas manchas, espinhas, rugas e dentes amarelos ao longo dos episódios. É raro encontrar séries adolescentes que não tenham representatividades vazias, com atores de 25 anos interpretando personagens de 16. Na trama, as imperfeições são apontadas e não há problema nenhum nisso.

O romance de Simon e Wilhelm toca todos os que assistem porque realmente parece de verdade. Não há hipersexualização e, ao mesmo tempo, não há puritanismo. Há o que sempre existe: jovens se descobrindo juntos e enfrentando problemas que todo LGBTQIA+ enfrenta. A insegurança e o medo em demonstrar o mínimo de afeto persegue todos da nossa comunidade, e todos os sentimentos são ainda mais experenciados quando você é da realeza monárquica e se apaixona por um garoto que mora no bairro mais pobre da cidade.

Personagens como Felice possuem corpos reais, fora do padrão de beleza inalcançável. Além disso, Sara e seu TDAH não são representados de forma a gerar ainda mais estereótipos e problematizações capacitistas. A realidade por trás de corpos e/ou deficiências reais faz com que os espectadores não se comparem ou se menosprezem, pois conseguem se enxergar ali dentro. Felice, como mulher preta, não é retratada como a personagem forte que deve lutar contra o racismo; Sara, por sua vez, não passa a série toda sofrendo capacitismo e precisando de ajuda alheia para conseguir realizar suas atividades.

É fato que Young Royals é uma série LGBTQIA+ feita para todos, não somente para o púbico LGBTQIA+. Fugindo dos padrões norte-americanos de produção, a série sueca tem adolescentes de verdade representando personagens que vivem problemas reais e que não são resumidos às suas minorias e vivências. Discutindo sobre a disputa de classes, a pressão da mídia, a busca por aceitação e fugindo de muitos estereótipos que poderiam ser reproduzidos, a produção teve muito respeito ao nos representar numa trama genuína, autêntica, envolvente e verdadeira.
`;
